[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "x86/x86-64"

[default_config.opts]
compiler = "x86_64-elf-gcc"
compile_flags_txt = ["-I./include"]
diagnostics = true
default_diagnostics = false
